variables: 
  certificate: &crt |
    -----BEGIN CERTIFICATE-----
    MIIFXzCCA0egAwIBAgIDEAISMA0GCSqGSIb3DQEBCwUAME4xCzAJBgNVBAYTAlVT
    MQ8wDQYDVQQIDAZEZW5pYWwxDDAKBgNVBAoMA0RpczEgMB4GA1UEAwwXd2ViYXBw
    LmlzdGlvaW5hY3Rpb24uaW8wHhcNMjEwNzA0MTI0OTMyWhcNNDEwNjI5MTI0OTMy
    WjBkMQswCQYDVQQGEwJVUzEPMA0GA1UECAwGRGVuaWFsMRQwEgYDVQQHDAtTcHJp
    bmdmaWVsZDEMMAoGA1UECgwDRGlzMSAwHgYDVQQDDBd3ZWJhcHAuaXN0aW9pbmFj
    dGlvbi5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK/YdDKdghWr
    yT4uJDQR1ajeV4THptsPi9594CxWcPJC7ub/YqtSMSzVoMgWf/ZlqCWQ22dBrmFk
    AP52AsOHKt2QeW3ZIw6Eh17dU37OSyYEbF5COKYz47lvU3BXas18rUL1Q/0LPdyp
    /5F5NdiIIkM5j0kIXHdUUKKr1FZY5meG04feJAQpj/kt6g9z28ArcGUbVutQH73j
    D3h4m3d3Jay27cY2qDM3dvd8QfzDNu3jb8NYpsBT2bcu40EDLQ5lOC0YRJgd29PN
    LI/UppERs/62rKZq+dVXN/6PunWkzJg/equA9tvkEzPxYJGe4YG7tcDuUcDu2mdz
    GyRv3yR1UXcCAwEAAaOCAS4wggEqMAkGA1UdEwQCMAAwEQYJYIZIAYb4QgEBBAQD
    AgZAMDMGCWCGSAGG+EIBDQQmFiRPcGVuU1NMIEdlbmVyYXRlZCBTZXJ2ZXIgQ2Vy
    dGlmaWNhdGUwHQYDVR0OBBYEFIcOXqRMpVfFbZeVZMR9YB67B5T0MIGQBgNVHSME
    gYgwgYWAFLnzhAgiNyzTdRjSB8RvTmepDH0UoWikZjBkMQswCQYDVQQGEwJVUzEP
    MA0GA1UECAwGRGVuaWFsMRQwEgYDVQQHDAtTcHJpbmdmaWVsZDEMMAoGA1UECgwD
    RGlzMSAwHgYDVQQDDBd3ZWJhcHAuaXN0aW9pbmFjdGlvbi5pb4IDEAISMA4GA1Ud
    DwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOC
    AgEARmCzAuNyZRgtzUhYKVoZJHk5TzzGxqNzXsiuv6b/TvT+TQvJPzlbQfy+/XLN
    edFIvXJFLrB/6jb/Mdnz/B+ctfqXVlRBE3h7cQz+fUyb2/t4qzOlaZZEXCJy62xc
    8UwQIFbU5NOK3pNjE3aCGoiu9db/TSdGyYQqsIjqfaMTrEwFF6s4zM0StrTF+VQu
    +1YP6cwCqJdD+cvQrhe1fPEILbg/6foQ0ugEQMbUeKHerq3wa+NQ1Buc2YOs6DjZ
    Yi1JGmiost1I8ul96NbMDIz8QlSoIIuUVYgUhZfMjAWRH85dJZckEpu43RxuYuO7
    lEVLkvEIYKIdt+d7Ae8NWT0v5G/nG/T2Sb6aJ+lzT+kmaYMYW7aaJ7kDX14ETK4g
    ISRGbLVfBF4uYLlBWY0hxvdVnHqQIcrnxlvnZXlmLbYejcdiCAr8BImMHYo4BJ3X
    YaAwAU8ZSma/pPvgf9h1KMKA0Fhb8ijJ5s60lXBvLRgzOz1eB8yVgApWFTjQ+hRk
    pM9Poo5OVoIYuI4SzHlBl1df2wGCmW6h+7OlJcn7m7ZYVO0/QYsie5sl1nqrRU9y
    28ZfATe9HnZETCOORCro8LD1mDHN9pNqR8acG0s1cRnsNyTbdIRJ4Pxg4K71t2rs
    NelTeXRTAz2iM7x5jxzzTa1Sv7T4TCHbuiUepUeYOdBVFjg=
    -----END CERTIFICATE-----
  key: &key |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAr9h0Mp2CFavJPi4kNBHVqN5XhMem2w+L3n3gLFZw8kLu5v9i
    q1IxLNWgyBZ/9mWoJZDbZ0GuYWQA/nYCw4cq3ZB5bdkjDoSHXt1Tfs5LJgRsXkI4
    pjPjuW9TcFdqzXytQvVD/Qs93Kn/kXk12IgiQzmPSQhcd1RQoqvUVljmZ4bTh94k
    BCmP+S3qD3PbwCtwZRtW61AfveMPeHibd3clrLbtxjaoMzd293xB/MM27eNvw1im
    wFPZty7jQQMtDmU4LRhEmB3b080sj9SmkRGz/raspmr51Vc3/o+6daTMmD96q4D2
    2+QTM/FgkZ7hgbu1wO5RwO7aZ3MbJG/fJHVRdwIDAQABAoIBAEpIcQW0vfAzqoam
    7UpFwnFcw7HmuVjO33I00I9KUNo2Zj+U4PSoeveKoyoDPzkyRm7gG58qAuVHXpgf
    +BjrL7N7RaCe2o1WdO0hKBVoRhygP7st1Ep5nxiFq8TIWOjHY1Xm0DrEFfTyp3Cn
    uJRpJbgqR5o9evo51vpxBfkYAvT2LvjSYXMgBnwkcWWane9JK/cBofapNDODWMj7
    cclkXQ22aoPzqmfcnRIquVz6uYRv45qU51FnxnhQV2FQik0e3DrNc9+7J2Bipezd
    DogIOT4nbH4trLP7l6YxOf6ZWupRu0JHNyeoPDRFYJlvwJttUXz/QUwfDS1RPojI
    aTFlueECgYEA5TBpu87nHaC7VoY4LUhS8eBkuOFn3v3wrwgbcwqDn2/hitj33YB9
    T6I7bbZ8PozXF1iaC8/4QOVQlmhlCYQTRCBUk0ZKs22C987gXohhAmku8p+7Hgvo
    2ObEftG0OzJ0j/vwzit2uYW6ZqP/fx6GUDmMhWyzo2gJxmYBiSXgwhECgYEAxGqL
    2Gxua1D6DCSLLmZSZMFEAwCyH3kOGvkpAfNoqOdLpugL/s8IHWBLwQ2QtaSQshbC
    eKrGLX2J3EccB4s77Itk6kKfaUesVyNeda9buxPA1FZRz0BQy0iShSU+swpyKOhy
    EMmCpa0NswsW03AzfhXs1ONeruFRdPpvPgmc0wcCgYAq0mnfCmCKW57FItzaMRo2
    UTvgg1UaCA5xVa1zSDKhlpDolXNycnB3cZNzA1ahhUUm+ooFzPzQe0gcYjMGnSPQ
    Zc4HmmmYrsx6qq+nWgnuHmMEOC4JBiaiaDOsklf/e4Tl5ifvDZXoQgE67kdto/Fq
    ieYkg9Pooya4aBS/YFFnUQKBgEVJzMFxJtamvz6vWYXpxKEUaHiiszNVEfvD74pn
    ooEK7u4XJ7wgrp0mTjLxJR5eykh4rOvCWpzLj2lskF+850u/tL7K98884Hfw2y6q
    yLJK+pgtRzjUWGwN0tozVFX2lmUF8s8nNvZZAN8rR0cZaqDM/TnwZ4NLqt+YRMve
    ujrbAoGBAL04BzlJBMtoT9lRMJsveiT364Eg3PKnF+b4FZctLDC64wAZ04b7Mm4P
    wfz+Xt6wjorvbj3XdWbgQNq/FBkeeqFXB88wC/WZSmyzN8gQaSXS8qSAMpKzoOXw
    KSgYWGmCLTKckavPKhMKps2wpY848gImQVK1DTnCO04+xPOb2mnz
    -----END RSA PRIVATE KEY-----
  caChain: &caChain |
    -----BEGIN CERTIFICATE-----
    MIIFlTCCA32gAwIBAgIDEAISMA0GCSqGSIb3DQEBCwUAMGQxCzAJBgNVBAYTAlVT
    MQ8wDQYDVQQIDAZEZW5pYWwxFDASBgNVBAcMC1NwcmluZ2ZpZWxkMQwwCgYDVQQK
    DANEaXMxIDAeBgNVBAMMF3dlYmFwcC5pc3Rpb2luYWN0aW9uLmlvMB4XDTIxMDcw
    NDEyNDkyOVoXDTQxMDYyOTEyNDkyOVowTjELMAkGA1UEBhMCVVMxDzANBgNVBAgM
    BkRlbmlhbDEMMAoGA1UECgwDRGlzMSAwHgYDVQQDDBd3ZWJhcHAuaXN0aW9pbmFj
    dGlvbi5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMlfkh6SHaR8
    KweBRIulWglHVCW4egMK8zSE7ZGUxFDOjcnvMCv5p3LKV/YCY69k5J6NVOr6wpqk
    tbMOripaEsQ6IkQvpHMzj1IQEefGz8d1Ms32sOlDc/lIx93p5Cksggd6nr0wTH4W
    EriJuJ3WzTeYmFNlJMt1mTc5djkKdcFIWEW2rkEN7i109aNecUS4iPhUsroZEpCI
    /Z1n+Gfq2dsOAPcfrHtY+KowJxMhruccORpTt0VxUKOvSbiFPtqAkyTeQbUHNMpS
    Uh/m2SWbY5mYLwn8ky2V7zaY0mt46C6OxNNT29muL5WCSUbCT3foNo26aZG1CSqn
    lge4MtoEXlxexgPHdxJrI2j/6NUCcqHTQtU0/BEz7zcD7Da6667xTTEh9LMIJoPK
    mEQQEvgYWlbx7QwXQGLkVrWwhlniyoQwKfBy3Cr4yhVjrQXDo9wTDoZjs7etDXaF
    XQIW0z8mFHiSQLT45c7vOkT9y8cFwoEMhFQOFbACAE8Y4I+7AvNUOoR8CVyCSt6b
    JbdChEAWVs+My+ZAGCNP647W0K4cNO/aHLp+YNjyG/iQPQIbGW5pEv85ISqcCGQX
    CTn3V+1BXc8o8LnXGZsC7G9bG2Yk9E8hMUqdsKkspZM0BY8+iG2qwl+4od876TFk
    QoygZf5Th2rB14WpmZ5isNoY0kAXubvpAgMBAAGjZjBkMB0GA1UdDgQWBBS584QI
    Ijcs03UY0gfEb05nqQx9FDAfBgNVHSMEGDAWgBRx64ugSfOyE2CCSxAYjsiFcz7Q
    aTASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0B
    AQsFAAOCAgEAdFONEjAXU38IA/D2gab4FCExq+sObFoOOwUYlnUwPUUzmsB/6rV/
    K6bf7yhm2zAloHBFxaQ4F/reXXmRV7++vP16d7r0U1zqxiwVp1OEIoFSrkNeTunM
    ECEIBNrmxncnvCCNz/654MVDCTfVBymhMtHNbkVeOq0itimS4IFCjgHSOxZJjW8e
    tcDj2XUpkQXuPyAHm9IGJxXlSnhbzXHbVbpiR7U8dmqMuhJ+37RziPpycTbN75PW
    YhvqYbxWbb249XtwoG0pkjP8efm7Pr2o36eyOuS9W/4zHZ4m5ZQ0XeE5QhV3HD0F
    gA0ocn7394MFM10Sy4zj417FIzyJ/MZ8xDOx7zGAbG3nwOsY1uWqI3IZRbpweVrN
    rFfi0jmf/7PI4KW9XQeQ6MOIY5QsJhj2gJyGYsbw/EwriFHopnmw/cChk+C5mNp6
    ZUG6+iMtWJsrUmrBZqYGL69NG760tOJlN2vFTCD5omeKpsNQW7qfZSmW1MKCKz5n
    yyk+21ry0V9WJAUGTRAngxlG2km8qzily9iJD+5XV5oOxdURvdgaaJc5wH5sVuyQ
    cvl4mqXGC7O5q7wQQ0rmCQLzEMpXnKXDYEnErIoj8gNWlhEVqa55ZLb8z5nbnjKD
    sWXNM0TF1ZL6mg8dUFoS8NPt4AvGwxMCE8NX7Ez+uIW9E2fg6Aw25A4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFrjCCA5agAwIBAgIJAPlSxA3cU9i4MA0GCSqGSIb3DQEBCwUAMGQxCzAJBgNV
    BAYTAlVTMQ8wDQYDVQQIDAZEZW5pYWwxFDASBgNVBAcMC1NwcmluZ2ZpZWxkMQww
    CgYDVQQKDANEaXMxIDAeBgNVBAMMF3dlYmFwcC5pc3Rpb2luYWN0aW9uLmlvMB4X
    DTIxMDcwNDEyNDkyOVoXDTQxMDYyOTEyNDkyOVowZDELMAkGA1UEBhMCVVMxDzAN
    BgNVBAgMBkRlbmlhbDEUMBIGA1UEBwwLU3ByaW5nZmllbGQxDDAKBgNVBAoMA0Rp
    czEgMB4GA1UEAwwXd2ViYXBwLmlzdGlvaW5hY3Rpb24uaW8wggIiMA0GCSqGSIb3
    DQEBAQUAA4ICDwAwggIKAoICAQDJzmkMzqJc7uqH9It2eDl64KsG5d5f3DjofWzE
    APczF2FMvRy3dAttxmALRmMOyE98XTKJc1h19J8WSxEav1U9NPH8yqHRWVxmiWtg
    r97vksGMDkVOFhjl86S4sif+uEj2omBGKGIikkPVQYX9ADaurwXIe3EvbIxFEXzd
    hYudDQcV0pR6g2tIvz25g6M7pHNpBe5oTDtxhqS/eqZZsddrbocPstRbUzzfOeGo
    HRIAvuQhtA1Gh8Sua+E9XBvNVQWG26vjmfIhN+wCWPobIgqAJe/RBuHrpUe1c8qz
    oMXys4mvz4l68DSpN/2V5mfPmURRABKok/TASdu05YIiE6MgjPQUCZNEJHKlVr3F
    WP8HXjP8eX02ULsqlS2C1wD1Lzk50OdtFNB+2IOs9zkckVJ9z7sbNPLiSrOMioLV
    m4NbSEu43HEwxwUFYInLHxrVq5a4RXkbKpwZ+2/1r+jdbsAgbAZ23Xb3h3g0Ik4L
    QE61FcIkLKrzbe5nmkCrfeM5K+bPe4RnVBGutv8HG0BZA73M4zVT+ZNI45X9jYwl
    UdSLgzn8F4ixBmvo0amXtSYHfGvZL6kzsWHQ6qhVSwuufTWe/CxCaiycLORVDSH9
    zr3NpRFYWtJ/3oGN/I3j+2lVaIZwdmbYLp+SUhwwFQOiXOQeOYSJs8lKL0reoHVt
    2yRpMwIDAQABo2MwYTAdBgNVHQ4EFgQUceuLoEnzshNggksQGI7IhXM+0GkwHwYD
    VR0jBBgwFoAUceuLoEnzshNggksQGI7IhXM+0GkwDwYDVR0TAQH/BAUwAwEB/zAO
    BgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQELBQADggIBAMFQSHWbc4uODQMDtGKu
    SGTQwDpN8hjhUx4hCLiy8mptaTH65X6RMBNJ1VqGlQVwubqBDpj9ouJBSAxYTyl4
    kanwyb01blEj8ZmmO5KrxMVNP3+pXud2GTHx8nXRs0x9NOv/9KMyGnYWYjzW0jAw
    4hO0drO10U79sHlGel1Z0RT2b7TUtapQQxW1H+5Ywmvnc35n3DC4V1RPnjocuS5l
    VauVhC1WbjmxZ9Snd+KI3HIhwxGI8kbenN7Nbdeg0kmjsDf/3YHmtF8nOKX/00i7
    4sq2+wJTWyr0PZYdEuo3rd/e3jNZFG081JWXa7B4KQq8SD2EXFq8C2sxX8H/GR7z
    nhzgKt/0B0R7nBNT65H/kOQLOduLTyepFSGM65BZqeD6z+UqMfW4sT3YADfEUn6Q
    OM6oDPxb8FwxnwEyoWU9XoiTsjvg6Xjcm0Nl+Pu9+7zYKYITmSSu+rNg+/gjohDq
    V7UzZFDxtWwnM61FAaJ6tAGOmxz86edvUrj/AKW0QHbJ7998WcrIDPhMEuPCRzFH
    +OjFAw+Fwi8NvABLQP+qaUOQ5uwsi2sOmEXfv3GlUuG9Lsxeea4dHmQFgBlISq5/
    zbgdXA0icHSDMWQ+l5mcrNaNLjKyUyvOkH/4ZvjTOwaLCXRexXX7HFm32q3YZWLh
    Yu91e2W4lkqQiQffDt/Xd9Iq
    -----END CERTIFICATE-----
  catalogCrt: &catalogCrt |
    -----BEGIN CERTIFICATE-----
    MIIFYjCCA0qgAwIBAgIDEAISMA0GCSqGSIb3DQEBCwUAME8xCzAJBgNVBAYTAlVT
    MQ8wDQYDVQQIDAZEZW5pYWwxDDAKBgNVBAoMA0RpczEhMB8GA1UEAwwYY2F0YWxv
    Zy5pc3Rpb2luYWN0aW9uLmlvMB4XDTIxMDcwNDEzMzAzOFoXDTQxMDYyOTEzMzAz
    OFowZTELMAkGA1UEBhMCVVMxDzANBgNVBAgMBkRlbmlhbDEUMBIGA1UEBwwLU3By
    aW5nZmllbGQxDDAKBgNVBAoMA0RpczEhMB8GA1UEAwwYY2F0YWxvZy5pc3Rpb2lu
    YWN0aW9uLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyKK9SItU
    lpPodACIKEjcmjG53QGZHET7FXSh6rstMpybqcZJJ7ESLQdwrdm3ilRAEZG4eIiI
    NnWasROUASsJDCmD92GpV5LlPOjlGXJaCVHdlJTO/Ufqzx9YCK3bvj2ZqySt9bjM
    UPpqrZqEZYXGRGdW4SD0sR+NqQuwuLgLizQXP752E1feux85EBD/i7bTzIfZCBSh
    5FI0pX5z5FFQlgqJFoNc3DErrUTuOXsXRybpgwOSByvofBQXDXXOTxGUzxWiCmpE
    XOwh96voBsmEQvlwe9Z7O+l8ERLpl1V+lYYjKzrsTZrVsdec2d64LYRmyIzguf9s
    sUrIf1wBftmAgQIDAQABo4IBLzCCASswCQYDVR0TBAIwADARBglghkgBhvhCAQEE
    BAMCBkAwMwYJYIZIAYb4QgENBCYWJE9wZW5TU0wgR2VuZXJhdGVkIFNlcnZlciBD
    ZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUhuflP24e5MBhkWhRctK3zJDTtucwgZEGA1Ud
    IwSBiTCBhoAUGk74lxUm7vI1O7yjmueoS0Cu3WihaaRnMGUxCzAJBgNVBAYTAlVT
    MQ8wDQYDVQQIDAZEZW5pYWwxFDASBgNVBAcMC1NwcmluZ2ZpZWxkMQwwCgYDVQQK
    DANEaXMxITAfBgNVBAMMGGNhdGFsb2cuaXN0aW9pbmFjdGlvbi5pb4IDEAISMA4G
    A1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsF
    AAOCAgEAOJAvnU9h/CEQtcYh8LloT4mO6UWXwkloNWziNM+AIPMrYvc9wUYC8zP1
    TuOjvOU0wUAxIIAy1ss8x8djaAussGVtqzH88f1hY/MuNB5PfihvfvGxI0TNmapG
    OJturyX0qzSIBEdY/KpIGK2xkQA37VngbfVb1CCBnJfIOy7HarmzLylJgh9mc35S
    DbYq5guEbkhUN7E4p7YRm9FpohhUAuOqG4+OMCXzNK/CWhaWyYLf99luV/Mln1Aq
    HfMwPaxcx7SanBz0DfzOPKnVpHHDUCdmTaufTbgzn6jWgfa7Ca8eBzIzkrUq9hFE
    uTsTjdUAcllobbbk5rox6Zp/xIfZhNfVHiA2pJVkVeptitJ6RYUP9zWEfhofxKva
    VC01J8AQl4T6wuC5x7u5zUh7/7NmlfCiFgn22dzkIcNvFh7Fi66u3pcwWHWFJ4sl
    TtRsj7Tk2rSbkbeVTIQbSdbl4AFfrJSbMhOTQD8nCixk2HZ+qOobPmFRSrSlYp+Y
    EJ2CUSsYxPLpyWKol2gNX0ZOenNZMjYqtcqr7Ux2Wj5DczoobNxwGTox8Pd4Iqi0
    sy602NHkdIKzgy+bOwJYVqtgskkZffg3bMfny3hfmJ/kaWHulni0YhHyMe2gtx+3
    v7VNQuCzFB5YLOLl47wJrHr63FbW5KBiUuS2UJ9SUwXkpu3BTEA=
    -----END CERTIFICATE-----
  catalogKey: &catalogKey |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyKK9SItUlpPodACIKEjcmjG53QGZHET7FXSh6rstMpybqcZJ
    J7ESLQdwrdm3ilRAEZG4eIiINnWasROUASsJDCmD92GpV5LlPOjlGXJaCVHdlJTO
    /Ufqzx9YCK3bvj2ZqySt9bjMUPpqrZqEZYXGRGdW4SD0sR+NqQuwuLgLizQXP752
    E1feux85EBD/i7bTzIfZCBSh5FI0pX5z5FFQlgqJFoNc3DErrUTuOXsXRybpgwOS
    ByvofBQXDXXOTxGUzxWiCmpEXOwh96voBsmEQvlwe9Z7O+l8ERLpl1V+lYYjKzrs
    TZrVsdec2d64LYRmyIzguf9ssUrIf1wBftmAgQIDAQABAoIBAChBJpMQiWcww9nK
    ZYcXn1M8mNrzwCGA4ZObdAUhit71tvGoO/M/vrLUJFJtNTsGzlf4Ebf1RMcQb3oJ
    wI8/cDBFgBm5OX29lkrTO2wQmmn2R+vQs3rz2/O0iTgskcMontVMpa6AZlX0+ERe
    lSO9ZFtDFJZUw2NqPkTleI6HNqG19dwUSFByL07q3QjL10GwKAmkFdZihLvdTEgO
    qzlUkYSRPYTkh1xo1KeeD/gDXSRzZrN+NSHamb0rm0CWbSbz8Xio9KkYvJjjPTId
    ei/9d5FsXVlyYJgfv4fjTU1jEiMeAU1Ld6MXs1kejruf0PynmpV6bZl+mI1ZKSqB
    d27n9QUCgYEA6aaspjZZR1c+3fEJwn0b+iBPiPHk9sqcI4KmSTlKhafyEGi+L2iU
    MIqD0mRpg/kbJx5ViozRO/G5DUK6Wgub3jNnsXKS8i/dOEf0JnfWSMjGceHPI6G9
    8qbmjC4vfjn0Y20+UzcMTM2odf5TtJ5WqFoDoPINpBgpO2On3DG8W5MCgYEA29Oh
    SsIFHko7bwF++Qp9JUt+qkI38MDuY2zi93HZgqhrkGi7TT73AVF3YxaEergLgNe5
    j++kQYDjCqUQz+DEzunSAors4Rs/RcnBImOPYjQhiP39GcInLrIOg9RWoApDapj/
    8rGaRBw83GdrEpSPZYO35U8xY2//kUf22SZryBsCgYAyQE2bhc7XwBTeSOvvb1bo
    CbDxZAz5YwQHwx6eWvsDGea+zrgwnA5bDj9hrYTgBGBpnmWJYdXSTZ+eEX7gxORl
    +qpPiLO/8LlkVF1XNKjaiIvdjFIveKbQnEKzXW+Ld01vYNxpq0oy7nxPvD4md3Nt
    y8ZCBC0Y4LVld35vpia7jwKBgQC+iLwwc+LD0kuZd456hWDbRohPQn4CKvd1Lhe7
    qe6BlUFGNcDCv2SQu+/i7s19ILC3yEOKQof4TqJ7w37C72smfPwOQCP5KQi6kJja
    GblZwR2gA6WxAdu8WZDDKvS6Wqr8ZgjSbqXrix4lW24u+J0hu/1UwENqkNTPM7T9
    mpOpKQKBgE3Fph08je0joeQxQu/jxlzYvV4d0P2dcID15aYFnzxfa9ePLiuq5wFp
    +eX3Z6GlKqKDB3b+j5Zm97sBc6Fl1LmgURGpFTI3mclOh0Y+rYTP6RQ8KG8sVfmY
    ntkqNkucMBvTLuWKXunCzrGre2I9yDZmjKIn94WaIrBecvAkZSee
    -----END RSA PRIVATE KEY-----



gateway:
  base: false
  simpleTls: false
  mTls: false
  multiMTls: true

secret:
  ingressGw:
    tlsCrt: *crt
    tlsKey: *key
    caCerts: *caChain
  webAppCredential:
    tlsCrt: *crt
    tlsKey: *key
  catalogCredential:
    tlsCrt: *catalogCrt
    tlsKey: *catalogKey